### ISSUE TITLE
常見用用於 UserDefinedDICT 的 key

### ISSUE THREAD

**Issue by Droidtown** [Intern-CD/SpendThrift_bot#3]
https://github.com/Intern-CD/SpendThrift_bot/blob/12e3816a1c1a83b4bd5f85fb7d9361b5487ee3fd/SpendThrift_bot/intent/Loki_spend_adv.py#L24

'money' 是太常見的一個字了。

由於 UserDefinedDICT 裡的 key 和 valueLIST 中的每一個 value 都會被拿來當做自訂詞，因此建議採用以下格式做為 key…

`_wordWord` 也就是一個底線，加上一個首字小寫的字，再加一個首字大寫的字。e.g., `_moneySpend`

**Comment by Grammyship** [comment]
已更正~
